root: true
env:
  es2018: true
  browser: true
  webextensions: true
extends:
  - eslint:recommended
  - plugin:vue/base
parser: vue-eslint-parser
parserOptions:
  parser: "@babel/eslint-parser"
  ecmaVersion: 2018
  sourceType: module
  ecmaFeatures:
    globalReturn: false
    impliedStrict: false
    jsx: false
rules:
  no-console: 0
globals:
  DEBUG: true
  PRODUCTION: true
  MOZ: true
  ga: true
